services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: brcruzfa2/neoform:1.0.0
    container_name: neoform_php
    restart: unless-stopped
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    volumes:
        - ./:/var/www/html
    networks:
        - neoform_network
    depends_on:
        - db
        - redis

  web:
    image: nginx:stable-alpine3.20-slim
    container_name: neoform_web
    restart: always
    ports:
        - "8000:80"
    volumes:
        - ./:/var/www/html
        - ./nginx:/etc/nginx/conf.d
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 30s
        timeout: 10s
        retries: 3
    depends_on:
        - app
    networks:
        - neoform_network

  db:
    image: postgres:17.3-alpine3.20
    container_name: neoform_db
    restart: always
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
        - 'neoform-db:/var/lib/postgresql/data'
    healthcheck:
        test:
            - CMD
            - pg_isready
            - '-q'
            - '-d'
            - '${DB_DATABASE}'
            - '-U'
            - '${DB_USERNAME}'
        retries: 3
        timeout: 5s
    ports:
        - "5432:5432"
    networks:
        - neoform_network

  redis:
    image: redis:8.0-M03-alpine3.21
    container_name: neoform_redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - 'neoform-redis:/data'
    networks:
        - neoform_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s


networks:
    neoform_network:
        driver: bridge

volumes:
    neoform-db:
        driver: local
    neoform-redis:
        driver: local
